### ISSUE TITLE
Refresh captcha and change error message

### ISSUE THREAD

**Issue by omarsafwany** [latrell/Captcha#2]
I have two issues:
1. Is there a way the captcha could be refreshed for another one if it wasn't clear?!
2.If the captcha doesn't match, I get the following 'validation.captcha'. Anyway I could change this message to other one?!

**Comment by Latrell** [comment]
1. For the browser cache, you can use JS to add a useless argument to force a refresh, such as:
```javascript
url + '?_=' + Math.random()
```

2. lang/xxx/validation.php language file, add the configuration `captcha`, such as:
```php
'captcha' => '验证码不正确。'
```
